### ISSUE TITLE
left button and scroll mouse problem

### ISSUE THREAD

**Issue by moebius1** [linuxwacom/input-wacom#137] opened 2019-11-09 10:14 UTC
Bonjour,
Since a long time, several months I think, wheel mouse of my graphire2 4x5 tablet don't work in QT programs like frescobaldi or kaffeine.
But now, after some updates (Witch ones ? I don't know) of my debian testing, left button don't work anymore too in some programs like vlc or kaffeine ; but on mate desktop, there is no problem.
lsmod | grep wacom :
wacom                 122880  0
usbhid                 65536  1 wacom
hid                   139264  3 wacom,usbhid,hid_generic
In synaptic, view the attached file.
![screenshot](https://user-images.githubusercontent.com/1695176/68526941-81650580-02e1-11ea-889c-6a4687f597a7.png)
I've tried a standard mouse : no problem
Well, tell me if you need something else.
Thank's for your help.
cordialement,

**Comment by jigpu** [comment] 2019-11-11 15:22
Likely a duplicate of https://github.com/linuxwacom/xf86-input-wacom/issues/93. Please try the workaround listed in that bug report and let us know if it doesn't work.

**Closed as completed by jigpu** 2019-11-11 15:22 UTC
